# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh in ang-ee/angee-operator.
# Every release overwrites this file — edit the generator, not this.
class Angee < Formula
  desc "Self-managed stack manager for agent-native applications"
  homepage "https://angee.ai"
  # No `version`: Homebrew scans 0.10.2 from the release URLs, and
  # `brew audit --strict` rejects declaring it twice.

  # process-compose runs `runtime: local` services. Installing it here also
  # bypasses angee's fallback path, which otherwise prompts to `go install` it
  # and needs a Go toolchain on the host.
  #
  # This points at our own vendored copy, not f1bonacc1/tap: Homebrew 6 will
  # not auto-tap a third-party dependency and additionally requires an explicit
  # `brew trust` for it, which would turn installation into three commands.
  #
  # git is not declared: Homebrew itself requires it, so it is always present.
  depends_on "ang-ee/tap/process-compose"

  on_macos do
    on_intel do
      url "https://github.com/ang-ee/angee-operator/releases/download/v0.10.2/angee-darwin-amd64.tar.gz"
      sha256 "b8a051543898ebfcdb2bcefd374e6a8e0be4b6db0a9faade968081ce5e377b7d"
    end
    on_arm do
      url "https://github.com/ang-ee/angee-operator/releases/download/v0.10.2/angee-darwin-arm64.tar.gz"
      sha256 "1b2b299652d40878b18f250684e0402b57319f4dd41c6d3d6f46fdb3381ffa9f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ang-ee/angee-operator/releases/download/v0.10.2/angee-linux-amd64.tar.gz"
      sha256 "629c531232c57e695f14ad4eccd624ef5d05c8e08072af4ea4f86346a04a10a7"
    end
    on_arm do
      url "https://github.com/ang-ee/angee-operator/releases/download/v0.10.2/angee-linux-arm64.tar.gz"
      sha256 "86d8bc9387de8502a6ca99050cc0b7b9995c6cfd8d063e59d9d991de2a0084d2"
    end
  end

  def install
    bin.install "angee"
    bin.install "angee-operator"
  end

  def caveats
    <<~CAVEATS
      Docker is NOT installed by this formula. It is required only for
      `runtime: container` services and container jobs. If you need it:

        brew install --cask docker      # Docker Desktop
        brew install --cask orbstack    # OrbStack
        brew install colima docker      # Colima + docker CLI

      `runtime: local` services use process-compose, installed as a dependency.
      A stack using neither needs no container runtime at all.

      Getting started:  https://docs.angee.ai/guide/getting-started
    CAVEATS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/angee --version")
    assert_match version.to_s, shell_output("#{bin}/angee-operator --version")

    # Exercise command wiring without reaching for a container runtime.
    system bin/"angee", "--help"
  end
end
