# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh in ang-ee/angee-operator.
# Every release overwrites this file — edit the generator, not this.
class Angee < Formula
  desc "Self-managed stack manager for agent-native applications"
  homepage "https://angee.ai"
  # No `version`: Homebrew scans 0.10.3 from the release URLs, and
  # `brew audit --strict` rejects declaring it twice.

  # process-compose runs `runtime: local` services. Installing it here also
  # bypasses angee's fallback path, which otherwise prompts to `go install` it
  # and needs a Go toolchain on the host.
  #
  # This points at our own vendored copy, not f1bonacc1/tap: Homebrew 6 will
  # not auto-tap a third-party dependency and additionally requires an explicit
  # `brew trust` for it, which would turn installation into three commands.
  #
  # git is not declared: Homebrew itself requires it, so it is always present.
  depends_on "ang-ee/tap/process-compose"

  on_macos do
    on_intel do
      url "https://github.com/ang-ee/angee-operator/releases/download/v0.10.3/angee-darwin-amd64.tar.gz"
      sha256 "ee73fc6c2a98487daee76f4db5e96b568d1943cdaa745f2a7c7f1fb2a7fda884"
    end
    on_arm do
      url "https://github.com/ang-ee/angee-operator/releases/download/v0.10.3/angee-darwin-arm64.tar.gz"
      sha256 "f13d2cc9f680c9077f09ba914e35089acfcae20a3262542f2ff46be5996b2f96"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ang-ee/angee-operator/releases/download/v0.10.3/angee-linux-amd64.tar.gz"
      sha256 "c70a764a03fb08dd15375cc0684dad9bab798980fb0c338a905498e6af37385f"
    end
    on_arm do
      url "https://github.com/ang-ee/angee-operator/releases/download/v0.10.3/angee-linux-arm64.tar.gz"
      sha256 "681670f6ffd4299779915a5a29dbc061e36ebe86e1ab96517d2c3f63b59f5faa"
    end
  end

  def install
    bin.install "angee"
    bin.install "angee-operator"
  end

  def caveats
    <<~CAVEATS
      Docker is NOT installed by this formula. It is required only for
      `runtime: container` services and container jobs. If you need it:

        brew install --cask docker      # Docker Desktop
        brew install --cask orbstack    # OrbStack
        brew install colima docker      # Colima + docker CLI

      `runtime: local` services use process-compose, installed as a dependency.
      A stack using neither needs no container runtime at all.

      Getting started:  https://docs.angee.ai/guide/getting-started
    CAVEATS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/angee --version")
    assert_match version.to_s, shell_output("#{bin}/angee-operator --version")

    # Exercise command wiring without reaching for a container runtime.
    system bin/"angee", "--help"
  end
end
