# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh in ang-ee/angee-operator.
# Every release overwrites this file — edit the generator, not this.
class Angee < Formula
  desc "Self-managed stack manager for agent-native applications"
  homepage "https://angee.ai"
  # No `version`: Homebrew scans 0.10.0 from the release URLs, and
  # `brew audit --strict` rejects declaring it twice.

  # process-compose runs `runtime: local` services. Installing it here also
  # bypasses angee's fallback path, which otherwise prompts to `go install` it
  # and needs a Go toolchain on the host.
  #
  # This points at our own vendored copy, not f1bonacc1/tap: Homebrew 6 will
  # not auto-tap a third-party dependency and additionally requires an explicit
  # `brew trust` for it, which would turn installation into three commands.
  #
  # git is not declared: Homebrew itself requires it, so it is always present.
  depends_on "ang-ee/tap/process-compose"

  on_macos do
    on_intel do
      url "https://github.com/ang-ee/angee-operator/releases/download/v0.10.0/angee-darwin-amd64.tar.gz"
      sha256 "2932b28cbf3a4f582ac31df5bd472680b3b8db4a01cac8cf14a4260b695b6e31"
    end
    on_arm do
      url "https://github.com/ang-ee/angee-operator/releases/download/v0.10.0/angee-darwin-arm64.tar.gz"
      sha256 "573b6e6b3d2c5389744d748472dd66e81327765d8ce02294b6558d67d26094ef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ang-ee/angee-operator/releases/download/v0.10.0/angee-linux-amd64.tar.gz"
      sha256 "ec9261513c185b307b8728d1dd95248aef09e8e317530cf6b8ec5b81adf2b977"
    end
    on_arm do
      url "https://github.com/ang-ee/angee-operator/releases/download/v0.10.0/angee-linux-arm64.tar.gz"
      sha256 "c53ee8e4f3c4eeba6e926471bfa5b749628d48f4d15db3ab323c085e66c0b4e5"
    end
  end

  def install
    bin.install "angee"
    bin.install "angee-operator"
  end

  def caveats
    <<~CAVEATS
      Docker is NOT installed by this formula. It is required only for
      `runtime: container` services and container jobs. If you need it:

        brew install --cask docker      # Docker Desktop
        brew install --cask orbstack    # OrbStack
        brew install colima docker      # Colima + docker CLI

      `runtime: local` services use process-compose, installed as a dependency.
      A stack using neither needs no container runtime at all.

      Getting started:  https://docs.angee.ai/guide/getting-started
    CAVEATS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/angee --version")
    assert_match version.to_s, shell_output("#{bin}/angee-operator --version")

    # Exercise command wiring without reaching for a container runtime.
    system bin/"angee", "--help"
  end
end
